# Common build stage
FROM node:14.14.0-alpine3.12 as common-build-stage

COPY . ./app

WORKDIR /app

RUN npm install

EXPOSE 5000

FROM common-build-stage as testnet-build-stage

ENV NODE_ENV testnet

CMD ["npm", "run", "testnet"]
