# Common build stage
FROM node:14.14.0-alpine3.12 as common-build-stage

COPY . ./app

WORKDIR /app

RUN npm install

EXPOSE 5000

FROM common-build-stage as mainnet-build-stage

ENV NODE_ENV mainnet

CMD ["npm", "run", "mainnet"]
